//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthosChronicle
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class VideoGallery
    {
        public int VideoId { get; set; }
        public int VideoSize { get; set; }
        public string FileName { get; set; }
        public byte[] VideoData { get; set; }
        public string Id { get; set; }
    }
    public partial class VideoGallery
    {
        public HttpPostedFileBase File { get; set; }
    }
}
